"""
Django settings for verity project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv
from redis import ConnectionPool

load_dotenv('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*8&vsq_a4((_^fcd5@93@=i58+1zj94g1d#@_of1!@)q((%#=v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django_dramatiq',
    'django_neomodel',
    'api.core',
    'api.user_management',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'user_management.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'verity.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'verity.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DRAMATIQ_BROKER = {
    'BROKER': 'dramatiq.brokers.redis.RedisBroker',
    'OPTIONS': {
        'url': 'redis://{host}:{port}/0'.format(
            host=os.environ.get('DRAMATIQ_REDIS_HOST', default='localhost'),
            port=os.environ.get('DRAMATIQ_REDIS_PORT', default=6379),
        ),
    },
    'MIDDLEWARE': [
        'dramatiq.middleware.Callbacks',
        'dramatiq.middleware.Retries',
        'django_dramatiq.middleware.DbConnectionsMiddleware',
        'django_dramatiq.middleware.AdminMiddleware',
    ],
}

DRAMATIQ_RESULT_BACKEND = {
    'BACKEND': 'dramatiq.results.backends.redis.RedisBackend',
    'BACKEND_OPTIONS': {
        'url': 'redis://{host}:{port}/1'.format(
            host=os.environ.get('DRAMATIQ_REDIS_HOST', default='localhost'),
            port=os.environ.get('DRAMATIQ_REDIS_PORT', default=6379),
        ),
    },
    'MIDDLEWARE_OPTIONS': {
        'result_ttl': 60000,
    },
}

REDIS_CONNECTION_POOL = ConnectionPool.from_url(
    DRAMATIQ_BROKER['OPTIONS']['url'], decode_responses=True)

DRAMATIQ_AUTODISCOVER_MODULES = [
    'tasks',
]

DRAMATIQ_QUEUES = ['default']

NEO4J_SCHEME = os.environ.get('NEO4J_SCHEME', 'bolt')
NEO4J_HOST = os.environ.get('NEO4J_HOST', 'localhost')
NEO4J_PORT = os.environ.get('NEO4J_PORT', '')
NEO4J_USER = os.environ.get('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.environ.get('NEO4J_PASSWORD', 'neo4j')

_neo4j_host = NEO4J_HOST if not NEO4J_PORT else f'{NEO4J_HOST}:{NEO4J_PORT}'

NEOMODEL_NEO4J_BOLT_URL = os.environ.get(
    'NEO4J_BOLT_URL',
    f'{NEO4J_SCHEME}://{NEO4J_USER}:{NEO4J_PASSWORD}@{_neo4j_host}',
)
NEOMODEL_SIGNALS = True
NEOMODEL_FORCE_TIMEZONE = False
NEOMODEL_MAX_CONNECTION_POOL_SIZE = int(
    os.environ.get('NEOMODEL_MAX_CONNECTION_POOL_SIZE', '50'))


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


PRELOADED_DATASETS = [
    {
        "name": "transactions",
        "kaggle": "mckenziemakwela/synthetic-global-bank-transactions-dataset",
    },
    {
        "name": "amlsim",
        "kaggle": "anshankul/ibm-amlsim-example-dataset",
    },
    {
        "name": "banksim",
        "kaggle": "ealaxi/banksim1",
    },
]

_seed_prod_limit = os.environ.get('SEED_PROD_LIMIT', '')
SEED_PROD_LIMIT = int(_seed_prod_limit) if _seed_prod_limit else None

SEED_DEV_LIMIT = int(os.environ.get('SEED_DEV_LIMIT', '500'))
