# Generated by Django 6.0.6 on 2026-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=50)),
                ('evidence_id', models.CharField(max_length=50)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_evidence',
                'constraints': [models.UniqueConstraint(fields=('case_id', 'evidence_id'), name='uniq_case_evidence')],
            },
        ),
    ]
